[package]
name = "signup-lambda"
version = "0.1.0"
edition = "2021"

[dependencies]

lambda_runtime = "1.0.1"
aws-sdk-cognitoidentityprovider = "1.105.0"
serde = "1"
tokio = { version = "1", features = ["macros"] }
aws-config = "1.8.12"
