[target.'cfg(target_os = "linux")']
rustflags = [
    "--cfg=web_sys_unstable_apis",
    "-C", "link-arg=-fuse-ld=mold"
]

[target.wasm32-unknown-unknown]
rustflags = ["--cfg=web_sys_unstable_apis"]

[target.'cfg(target_os = "windows")']
rustflags = ["--cfg=web_sys_unstable_apis"]
